from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date, time, datetime
from uuid import UUID
from enum import Enum

class Role(str, Enum):
    LEARNER = "learner"
    PARENT = "parent"
    EDUCATOR = "educator"

class Track(str, Enum):
    STEM = "STEM"
    SOCIAL_SCIENCES = "Social Sciences"
    ARTS_SPORTS = "Arts & Sports"
    VOCATIONAL = "Vocational"
    NONE = "None"

class ProfileBase(BaseModel):
    full_name: str
    role: Role
    grade_level: Optional[str] = None
    track: Optional[Track] = None

class ProfileCreate(ProfileBase):
    pass

class ProfileOut(ProfileBase):
    id: UUID
    created_at: datetime
    class Config:
        from_attributes = True

# --- Timetable Models ---

class ActivityType(str, Enum):
    LESSON = "lesson"
    PRACTICAL = "practical"
    BREAK = "break"
    ASSESSMENT = "assessment"

class TimetableEntryBase(BaseModel):
    day_of_week: int = Field(..., ge=1, le=5, description="1=Monday, 5=Friday")
    start_time: time
    end_time: time
    subject_id: Optional[UUID] = None
    activity_type: ActivityType
    notes: Optional[str] = None

class TimetableEntryCreate(TimetableEntryBase):
    pass

class TimetableEntryOut(TimetableEntryBase):
    id: UUID
    subject_name: Optional[str] = None # For display
    class Config:
        from_attributes = True

class TimetableBase(BaseModel):
    learner_id: UUID
    week_start_date: date
    term: int = Field(..., ge=1, le=3)
    grade_level: Optional[str] = None # Optional override for testing/MVP

class TimetableCreate(TimetableBase):
    pass # Entries are generated by the system

class TimetableOut(TimetableBase):
    id: UUID
    created_at: datetime
    entries: List[TimetableEntryOut] = []
    class Config:
        from_attributes = True

# --- SBA Models ---

class KNECScore(str, Enum):
    EE1 = "EE1"
    EE2 = "EE2"
    ME1 = "ME1"
    ME2 = "ME2"
    AE1 = "AE1"
    AE2 = "AE2"
    BE1 = "BE1"
    BE2 = "BE2"

class SBARecordBase(BaseModel):
    learner_id: UUID
    learning_outcome_id: UUID
    score: KNECScore
    comments: Optional[str] = None
    grade_level: Optional[str] = "Grade 4"
    academic_year: Optional[int] = 2026
    term: Optional[int] = 1

class SBARecordCreate(SBARecordBase):
    pass

class SBARecordOut(SBARecordBase):
    id: UUID
    recorded_at: datetime
    parent_acknowledged: bool
    outcome_description: Optional[str] = None
    outcome_code: Optional[str] = None
    mastery_probability: Optional[float] = None
    class Config:
        from_attributes = True

# --- Mock Exam Models ---

class QuestionType(str, Enum):
    MCQ = "multiple_choice"
    SHORT_ANSWER = "short_answer"

class Question(BaseModel):
    id: str
    text: str
    type: QuestionType
    options: Optional[List[str]] = None
    correct_answer: Optional[str] = None
    subject: str

class MockExamRequest(BaseModel):
    grade_level: str = "Grade 9"
    subjects: Optional[List[str]] = None # If None, generate for all core subjects

class MockExamResponse(BaseModel):
    title: str
    grade_level: str
    questions: List[Question]

# --- Notification Models ---

class NotificationType(str, Enum):
    INTERVENTION = "intervention"
    ALERT = "alert"
    SYSTEM = "system"

class NotificationBase(BaseModel):
    learner_id: UUID
    title: str
    message: str
    type: NotificationType = NotificationType.INTERVENTION
    metadata: Optional[dict] = None

class NotificationCreate(NotificationBase):
    pass

class NotificationOut(NotificationBase):
    id: UUID
    is_read: bool
    created_at: datetime
    class Config:
        from_attributes = True
